SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `zzz_address`;
DROP TABLE IF EXISTS `zzz_car`;
DROP TABLE IF EXISTS `zzz_corporate`;
DROP TABLE IF EXISTS `zzz_customer`;
DROP TABLE IF EXISTS `zzz_discount`;
DROP TABLE IF EXISTS `zzz_disccorp`;
DROP TABLE IF EXISTS `zzz_discindi`;
DROP TABLE IF EXISTS `zzz_individual`;
DROP TABLE IF EXISTS `zzz_invoice`;
DROP TABLE IF EXISTS `zzz_office`;
DROP TABLE IF EXISTS `zzz_order`;
DROP TABLE IF EXISTS `zzz_payment`;
DROP TABLE IF EXISTS `zzz_vehicle`;
SET FOREIGN_KEY_CHECKS = 1;